BlessedHub/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace BlessedHub.Controllers
{
    
    
    public class PortfolioController : Controller
    {
        
        public ActionResult OneColumn()
        {
            return View();
        }
        
        public ActionResult TwoColumn()
        {
            return View();
        }
        
        public ActionResult ThreeColumn()
        {
            return View();
        }
        
        public ActionResult FourColumn()
        {
            return View();
        }
        
        public ActionResult SingleItem()
        {
            return View();
        }
    }
}

BlessedHub/Views/Portfolio/FourColumn.cshtml
@{
    ViewBag.Title = "Four Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Four Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li class="active">Four Column Portfolio</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
        <div class="col-md-3 portfolio-item">
            <a href="@Url.Action("SingleItem")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

BlessedHub/Views/Portfolio/OneColumn.cshtml
@{
    ViewBag.Title = "One Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                One Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                  @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">One Column Portfolio</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

BlessedHub/Views/Portfolio/SingleItem.cshtml
@{
    ViewBag.Title = "Single Portfolio Item";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Single Portfolio Item
                <small>Explain Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Single Portfolio Item</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <img src="http://placehold.it/750x500" class="img-responsive">
        </div>
        <div class="col-md-4">
            <h3>Project Description</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <h3>Project Details</h3>
            <ul>
                <li>Lorem Ipsum</li>
                <li>Dolor Sit Amet</li>
                <li>Consectetur</li>
                <li>Adipiscing Elit</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Related Projects</h3>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img src="http://placehold.it/500x300" class="img-responsive img-customer">
            </a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img src="http://placehold.it/500x300" class="img-responsive img-customer">
            </a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img src="http://placehold.it/500x300" class="img-responsive img-customer">
            </a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img src="http://placehold.it/500x300" class="img-responsive img-customer">
            </a>
        </div>
    </div>
</div>

BlessedHub/Views/Portfolio/ThreeColumn.cshtml
@{
    ViewBag.Title = "Three Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Three Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Three Column Portfolio</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

BlessedHub/Views/Portfolio/TwoColumn.cshtml
@{
    ViewBag.Title = "Two Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Two Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Two Column Portfolio</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
               @Html.ActionLink("Project Name","SingleItem","Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>